/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Unauthenticated liveness check — what CI and Render's health probe hit.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whoami
         * @description Proves the auth dependency end to end: reject anything that isn't a
         *     live Firebase ID token or a valid backend session JWT; otherwise return
         *     exactly what was verified.
         */
        get: operations["whoami_api_v1_auth_whoami_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Phone
         * @description Whether a farmer with this phone exists — lets the login screen pick
         *     the "enter PIN" vs "register" path. Deliberately says nothing about
         *     whether a PIN is set or anything else about the account.
         */
        get: operations["lookup_phone_api_v1_auth_lookup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Create a PIN account and hand back a session JWT.
         */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Verify phone + PIN, issue a session JWT.
         *
         *     One 401 for both "no such phone" and "wrong PIN" — the caller learns
         *     nothing it couldn't already get from `/auth/lookup`.
         */
        post: operations["create_session_api_v1_auth_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Crop Catalog
         * @description List available crops from the catalog, cursor-paginated.
         */
        get: operations["list_crop_catalog_api_v1_reference_crops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/expense-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Expense Categories
         * @description List available expense categories, cursor-paginated.
         */
        get: operations["list_expense_categories_api_v1_reference_expense_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reference/activity-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activity Types
         * @description List available activity types, cursor-paginated.
         */
        get: operations["list_activity_types_api_v1_reference_activity_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/seed-reference-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seed Reference Data
         * @description Seed reference tables with initial data.
         *
         *     Idempotent: skips records that already exist (by name).
         */
        post: operations["seed_reference_data_api_v1_admin_seed_reference_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Farmer
         * @description Get the current authenticated farmer, provisioning on first call.
         *
         *     JIT-creates a farmer row on first successful token verification, then
         *     returns it. Subsequent calls fetch the existing row.
         *
         *     Requires a valid, current Firebase ID token with the correct audience.
         */
        get: operations["get_current_farmer_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Farms
         * @description List farms for the current farmer, cursor-paginated.
         */
        get: operations["list_farms_api_v1_farms_get"];
        put?: never;
        /**
         * Create Farm
         * @description Create a new farm.
         */
        post: operations["create_farm_api_v1_farms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Farm
         * @description Get a single farm by ID.
         */
        get: operations["get_farm_api_v1_farms__farm_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Farm
         * @description Soft-delete a farm.
         */
        delete: operations["delete_farm_api_v1_farms__farm_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Farm
         * @description Update a farm.
         */
        patch: operations["update_farm_api_v1_farms__farm_id__patch"];
        trace?: never;
    };
    "/api/v1/lands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Lands
         * @description List lands for the current farmer, cursor-paginated.
         */
        get: operations["list_lands_api_v1_lands_get"];
        put?: never;
        /**
         * Create Land
         * @description Create a new land.
         */
        post: operations["create_land_api_v1_lands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lands/{land_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Land
         * @description Get a single land by ID.
         */
        get: operations["get_land_api_v1_lands__land_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Land
         * @description Soft-delete a land.
         */
        delete: operations["delete_land_api_v1_lands__land_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Land
         * @description Update a land.
         */
        patch: operations["update_land_api_v1_lands__land_id__patch"];
        trace?: never;
    };
    "/api/v1/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Crops
         * @description List crops for the current farmer, cursor-paginated.
         */
        get: operations["list_crops_api_v1_crops_get"];
        put?: never;
        /**
         * Create Crop
         * @description Create a new crop.
         */
        post: operations["create_crop_api_v1_crops_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crops/{crop_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Crop
         * @description Get a single crop by ID.
         */
        get: operations["get_crop_api_v1_crops__crop_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Crop
         * @description Soft-delete a crop.
         */
        delete: operations["delete_crop_api_v1_crops__crop_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Crop
         * @description Update a crop.
         */
        patch: operations["update_crop_api_v1_crops__crop_id__patch"];
        trace?: never;
    };
    "/api/v1/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activities
         * @description List activities for the current farmer, cursor-paginated.
         */
        get: operations["list_activities_api_v1_activities_get"];
        put?: never;
        /**
         * Create Activity
         * @description Create a new activity.
         */
        post: operations["create_activity_api_v1_activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Activity
         * @description Get a single activity by ID.
         */
        get: operations["get_activity_api_v1_activities__activity_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Activity
         * @description Soft-delete an activity.
         */
        delete: operations["delete_activity_api_v1_activities__activity_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Activity
         * @description Update an activity.
         */
        patch: operations["update_activity_api_v1_activities__activity_id__patch"];
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/expenses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activity Expenses
         * @description List expenses for a specific activity, cursor-paginated.
         */
        get: operations["list_activity_expenses_api_v1_activities__activity_id__expenses_get"];
        put?: never;
        /**
         * Create Activity Expense
         * @description Create a new expense for an activity.
         */
        post: operations["create_activity_expense_api_v1_activities__activity_id__expenses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/expenses/{expense_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Activity Expense
         * @description Soft-delete an expense for an activity.
         */
        delete: operations["delete_activity_expense_api_v1_activities__activity_id__expenses__expense_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Activity Expense
         * @description Update an expense for an activity.
         */
        patch: operations["update_activity_expense_api_v1_activities__activity_id__expenses__expense_id__patch"];
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Activity Attachments
         * @description List attachments for a specific activity, cursor-paginated.
         */
        get: operations["list_activity_attachments_api_v1_activities__activity_id__attachments_get"];
        put?: never;
        /**
         * Create Activity Attachment
         * @description Create a new attachment for an activity.
         */
        post: operations["create_activity_attachment_api_v1_activities__activity_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activities/{activity_id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Activity Attachment
         * @description Soft-delete an attachment for an activity.
         */
        delete: operations["delete_activity_attachment_api_v1_activities__activity_id__attachments__attachment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Push
         * @description Drain a batch of outbox mutations. Per-item results: one bad item
         *     (a stale FK, a conflicting id) never fails the rest of the batch, and
         *     replaying the same batch again changes nothing (idempotent upsert by
         *     the client-minted id).
         */
        post: operations["push_api_v1_sync_push_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/pull": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull
         * @description Delta pull since a watermark, tombstones included, per entity type.
         *
         *     First call: pass `since` (omit for a full pull). If the response's
         *     `next_cursor` is set, at least one entity type had more than `limit`
         *     rows in this window — call again with that `cursor` (keep `since` as
         *     sent, it's ignored once a cursor is present) until `next_cursor` comes
         *     back null, then store the response's `server_time` as the new `since`
         *     watermark for the next pull.
         */
        get: operations["pull_api_v1_sync_pull_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActivityAttachmentCreate
         * @description Create an activity attachment (activity_id is from URL path).
         */
        ActivityAttachmentCreate: {
            /** Storage Key */
            storage_key: string;
            /** Content Type */
            content_type?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
        };
        /**
         * ActivityAttachmentRead
         * @description Read an activity attachment record.
         */
        ActivityAttachmentRead: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /** Storage Key */
            storage_key: string;
            /** Content Type */
            content_type?: string | null;
            /** Size Bytes */
            size_bytes?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /**
         * ActivityCreate
         * @description Create an activity.
         */
        ActivityCreate: {
            /**
             * Activity Type Id
             * Format: uuid
             */
            activity_type_id: string;
            /** Crop Id */
            crop_id?: string | null;
            /** Land Id */
            land_id?: string | null;
            /** Parent Activity Id */
            parent_activity_id?: string | null;
            /** Custom Activity Name */
            custom_activity_name?: string | null;
            /** Date */
            date?: string | null;
            /** Season */
            season?: string | null;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Notes */
            notes?: string | null;
            /** Activity Meta */
            activity_meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ActivityExpenseCreate
         * @description Create an activity expense (activity_id is from URL path).
         */
        ActivityExpenseCreate: {
            /**
             * Expense Category Id
             * Format: uuid
             */
            expense_category_id: string;
            /** Item Id */
            item_id?: string | null;
            /** Resource Id */
            resource_id?: string | null;
            /** Quantity */
            quantity?: number | string | null;
            /** Unit */
            unit?: string | null;
            /** Rate */
            rate?: number | string | null;
            /** Amount */
            amount?: number | string | null;
            /** Remarks */
            remarks?: string | null;
        };
        /**
         * ActivityExpenseRead
         * @description Read an activity expense record.
         */
        ActivityExpenseRead: {
            /**
             * Activity Id
             * Format: uuid
             */
            activity_id: string;
            /**
             * Expense Category Id
             * Format: uuid
             */
            expense_category_id: string;
            /** Item Id */
            item_id?: string | null;
            /** Resource Id */
            resource_id?: string | null;
            /** Quantity */
            quantity?: string | null;
            /** Unit */
            unit?: string | null;
            /** Rate */
            rate?: string | null;
            /** Amount */
            amount?: string | null;
            /** Remarks */
            remarks?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /**
         * ActivityExpenseUpdate
         * @description Update activity expense fields.
         */
        ActivityExpenseUpdate: {
            /** Expense Category Id */
            expense_category_id?: string | null;
            /** Item Id */
            item_id?: string | null;
            /** Resource Id */
            resource_id?: string | null;
            /** Quantity */
            quantity?: number | string | null;
            /** Unit */
            unit?: string | null;
            /** Rate */
            rate?: number | string | null;
            /** Amount */
            amount?: number | string | null;
            /** Remarks */
            remarks?: string | null;
        };
        /**
         * ActivityRead
         * @description Read an activity record.
         */
        ActivityRead: {
            /**
             * Activity Type Id
             * Format: uuid
             */
            activity_type_id: string;
            /** Crop Id */
            crop_id?: string | null;
            /** Land Id */
            land_id?: string | null;
            /** Parent Activity Id */
            parent_activity_id?: string | null;
            /** Custom Activity Name */
            custom_activity_name?: string | null;
            /** Date */
            date?: string | null;
            /** Season */
            season?: string | null;
            /**
             * Status
             * @default pending
             */
            status: string;
            /** Notes */
            notes?: string | null;
            /** Activity Meta */
            activity_meta?: {
                [key: string]: unknown;
            } | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Farmer Id
             * Format: uuid
             */
            farmer_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /**
         * ActivityUpdate
         * @description Update activity fields.
         */
        ActivityUpdate: {
            /** Activity Type Id */
            activity_type_id?: string | null;
            /** Crop Id */
            crop_id?: string | null;
            /** Land Id */
            land_id?: string | null;
            /** Parent Activity Id */
            parent_activity_id?: string | null;
            /** Custom Activity Name */
            custom_activity_name?: string | null;
            /** Date */
            date?: string | null;
            /** Season */
            season?: string | null;
            /** Status */
            status?: string | null;
            /** Notes */
            notes?: string | null;
            /** Activity Meta */
            activity_meta?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * CropCreate
         * @description Create a crop.
         */
        CropCreate: {
            /**
             * Land Id
             * Format: uuid
             */
            land_id: string;
            /**
             * Crop Catalog Id
             * Format: uuid
             */
            crop_catalog_id: string;
            /** Label */
            label?: string | null;
            /** Area */
            area?: number | string | null;
            /**
             * Area Unit
             * @default sq_m
             */
            area_unit: string;
            /** Season */
            season?: string | null;
            /** Sowing Date */
            sowing_date?: string | null;
            /** Current Stage */
            current_stage?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Expected Harvest Date */
            expected_harvest_date?: string | null;
        };
        /**
         * CropRead
         * @description Read a crop record.
         */
        CropRead: {
            /**
             * Land Id
             * Format: uuid
             */
            land_id: string;
            /**
             * Crop Catalog Id
             * Format: uuid
             */
            crop_catalog_id: string;
            /** Label */
            label?: string | null;
            /** Area */
            area?: string | null;
            /**
             * Area Unit
             * @default sq_m
             */
            area_unit: string;
            /** Season */
            season?: string | null;
            /** Sowing Date */
            sowing_date?: string | null;
            /** Current Stage */
            current_stage?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /** Expected Harvest Date */
            expected_harvest_date?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Farmer Id
             * Format: uuid
             */
            farmer_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /**
         * CropUpdate
         * @description Update crop fields.
         */
        CropUpdate: {
            /** Label */
            label?: string | null;
            /** Area */
            area?: number | string | null;
            /** Area Unit */
            area_unit?: string | null;
            /** Season */
            season?: string | null;
            /** Sowing Date */
            sowing_date?: string | null;
            /** Current Stage */
            current_stage?: string | null;
            /** Status */
            status?: string | null;
            /** Expected Harvest Date */
            expected_harvest_date?: string | null;
        };
        /**
         * FarmCreate
         * @description Create a farm.
         */
        FarmCreate: {
            /** Name */
            name: string;
            /** Area */
            area?: number | string | null;
            /**
             * Area Unit
             * @default sq_m
             */
            area_unit: string;
            /** Water Source */
            water_source?: string | null;
            /** Irrigation Type */
            irrigation_type?: string | null;
            /** Farming Method */
            farming_method?: string | null;
            /** Location Type */
            location_type?: string | null;
            /** State */
            state?: string | null;
            /** District */
            district?: string | null;
            /** Village */
            village?: string | null;
            /** Pincode */
            pincode?: string | null;
            /** Lat */
            lat?: number | string | null;
            /** Lng */
            lng?: number | string | null;
        };
        /**
         * FarmRead
         * @description Read a farm record.
         */
        FarmRead: {
            /** Name */
            name: string;
            /** Area */
            area?: string | null;
            /**
             * Area Unit
             * @default sq_m
             */
            area_unit: string;
            /** Water Source */
            water_source?: string | null;
            /** Irrigation Type */
            irrigation_type?: string | null;
            /** Farming Method */
            farming_method?: string | null;
            /** Location Type */
            location_type?: string | null;
            /** State */
            state?: string | null;
            /** District */
            district?: string | null;
            /** Village */
            village?: string | null;
            /** Pincode */
            pincode?: string | null;
            /** Lat */
            lat?: string | null;
            /** Lng */
            lng?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Farmer Id
             * Format: uuid
             */
            farmer_id: string;
            /** Setup Completed */
            setup_completed: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /**
         * FarmUpdate
         * @description Update farm fields.
         */
        FarmUpdate: {
            /** Name */
            name?: string | null;
            /** Area */
            area?: number | string | null;
            /** Area Unit */
            area_unit?: string | null;
            /** Water Source */
            water_source?: string | null;
            /** Irrigation Type */
            irrigation_type?: string | null;
            /** Farming Method */
            farming_method?: string | null;
            /** Location Type */
            location_type?: string | null;
            /** State */
            state?: string | null;
            /** District */
            district?: string | null;
            /** Village */
            village?: string | null;
            /** Pincode */
            pincode?: string | null;
            /** Lat */
            lat?: number | string | null;
            /** Lng */
            lng?: number | string | null;
        };
        /**
         * FarmerRead
         * @description Read a farmer record (current authenticated farmer).
         */
        FarmerRead: {
            /** Full Name */
            full_name?: string | null;
            /** Email */
            email?: string | null;
            /**
             * Preferred Language
             * @default en
             */
            preferred_language: string;
            /** Phone */
            phone?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Auth Uid */
            auth_uid: string;
            /** User Role */
            user_role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LandCreate
         * @description Create a land.
         */
        LandCreate: {
            /** Name */
            name: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Area Sq M */
            area_sq_m?: number | string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * LandRead
         * @description Read a land record.
         */
        LandRead: {
            /** Name */
            name: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Area Sq M */
            area_sq_m?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Farmer Id
             * Format: uuid
             */
            farmer_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Deleted At */
            deleted_at?: string | null;
        };
        /**
         * LandUpdate
         * @description Update land fields.
         */
        LandUpdate: {
            /** Name */
            name?: string | null;
            /** Area Sq M */
            area_sq_m?: number | string | null;
            /** Notes */
            notes?: string | null;
        };
        /** PhoneLookupResponse */
        PhoneLookupResponse: {
            /** Exists */
            exists: boolean;
        };
        /**
         * RegisterRequest
         * @description Create a PIN account.
         */
        RegisterRequest: {
            /** Phone */
            phone: string;
            /** Pin */
            pin: string;
            /** Full Name */
            full_name: string;
            /**
             * Preferred Language
             * @default en
             */
            preferred_language: string;
        };
        /**
         * SessionRequest
         * @description Log in an existing PIN account.
         */
        SessionRequest: {
            /** Phone */
            phone: string;
            /** Pin */
            pin: string;
        };
        /**
         * SessionResponse
         * @description A freshly issued session JWT plus the farmer it belongs to.
         */
        SessionResponse: {
            /** Token */
            token: string;
            farmer: components["schemas"]["FarmerRead"];
        };
        /**
         * SyncEntityPage
         * @description One entity type's slice of a pull response.
         */
        SyncEntityPage: {
            /** Items */
            items: {
                [key: string]: unknown;
            }[];
            /** Has More */
            has_more: boolean;
        };
        /**
         * SyncPullResponse
         * @description Delta since a watermark, per entity type, tombstones included.
         *
         *     `next_cursor` is set only while any entity type still has more of the
         *     current window to drain; once it's null the client stores
         *     `server_time` as its new watermark for the next pull's `since`.
         */
        SyncPullResponse: {
            /** Entities */
            entities: {
                [key: string]: components["schemas"]["SyncEntityPage"];
            };
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Server Time
             * Format: date-time
             */
            server_time: string;
        };
        /**
         * SyncPushItem
         * @description One outbox mutation. `id` is the client-minted UUIDv7 — the server
         *     upserts by this primary key, so replaying the same item is a no-op.
         */
        SyncPushItem: {
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "farms" | "lands" | "crops" | "activities";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Operation
             * @enum {string}
             */
            operation: "create" | "update" | "delete";
            /**
             * Payload
             * @default {}
             */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * SyncPushRequest
         * @description A batch of outbox mutations, possibly spanning entity types.
         */
        SyncPushRequest: {
            /** Operations */
            operations: components["schemas"]["SyncPushItem"][];
        };
        /** SyncPushResponse */
        SyncPushResponse: {
            /** Results */
            results: components["schemas"]["SyncPushResultItem"][];
        };
        /**
         * SyncPushResultItem
         * @description Per-item result — one bad item never fails the rest of the batch.
         */
        SyncPushResultItem: {
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "farms" | "lands" | "crops" | "activities";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Operation
             * @enum {string}
             */
            operation: "create" | "update" | "delete";
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Entity */
            entity?: {
                [key: string]: unknown;
            } | null;
            /** Error Code */
            error_code?: string | null;
            /** Message */
            message?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    whoami_api_v1_auth_whoami_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_phone_api_v1_auth_lookup_get: {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneLookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_auth_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crop_catalog_api_v1_reference_crops_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_expense_categories_api_v1_reference_expense_categories_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activity_types_api_v1_reference_activity_types_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    seed_reference_data_api_v1_admin_seed_reference_data_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_current_farmer_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmerRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_farms_api_v1_farms_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_farm_api_v1_farms_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_farm_api_v1_farms__farm_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_farm_api_v1_farms__farm_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_farm_api_v1_farms__farm_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lands_api_v1_lands_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_land_api_v1_lands_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LandCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_land_api_v1_lands__land_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                land_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_land_api_v1_lands__land_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                land_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_land_api_v1_lands__land_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                land_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LandUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LandRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crops_api_v1_crops_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_crop_api_v1_crops_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CropCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_crop_api_v1_crops__crop_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                crop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_crop_api_v1_crops__crop_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                crop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_crop_api_v1_crops__crop_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                crop_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CropUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_v1_activities_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_activity_api_v1_activities_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_v1_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_activity_api_v1_activities__activity_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_activity_api_v1_activities__activity_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activity_expenses_api_v1_activities__activity_id__expenses_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_activity_expense_api_v1_activities__activity_id__expenses_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityExpenseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityExpenseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_activity_expense_api_v1_activities__activity_id__expenses__expense_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_activity_expense_api_v1_activities__activity_id__expenses__expense_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
                expense_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityExpenseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityExpenseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activity_attachments_api_v1_activities__activity_id__attachments_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_activity_attachment_api_v1_activities__activity_id__attachments_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityAttachmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityAttachmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_activity_attachment_api_v1_activities__activity_id__attachments__attachment_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                activity_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_api_v1_sync_push_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncPushRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPushResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pull_api_v1_sync_pull_get: {
        parameters: {
            query?: {
                since?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncPullResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
