/**
 * Canonical database schema definition.
 *
 * Single source of truth for entity definitions, bridging Firebase (current)
 * and Postgres (future). Each entity includes field definitions with both
 * TypeScript and SQL type representations to prevent drift between
 * representations.
 */

// Field definition: name, TypeScript type, SQL type, nullability, constraints
interface SchemaField {
  name: string;
  tsType: string;
  sqlType: string;
  nullable: boolean;
  pk?: boolean;
  fk?: { table: string; column: string };
  unique?: boolean;
  arrayOf?: boolean;
  description?: string;
}

interface SchemaEntity {
  name: string;
  description?: string;
  source: string; // Reference to real source file/interface
  fields: SchemaField[];
}

export const schema: SchemaEntity[] = [
  {
    name: 'farmer',
    description: 'User account and profile',
    source: 'projects/home/src/app/models/farmer-registration.models.ts#FarmerRegistrationData',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
        description: 'Firebase Auth UID (email-based)',
      },
      {
        name: 'email',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
        unique: true,
      },
      {
        name: 'name',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
      },
      {
        name: 'location',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'experience',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
        description: 'Free-text farming experience level/description',
      },
      {
        name: 'crops_interested',
        tsType: 'string[]',
        sqlType: 'text[]',
        nullable: true,
        arrayOf: true,
      },
      {
        name: 'user_role',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
        description: 'Unconstrained free-text role; proposed RBAC not yet wired',
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
      {
        name: 'updated_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
      {
        name: 'deleted_at',
        tsType: 'datetime | null',
        sqlType: 'timestamp with time zone',
        nullable: true,
      },
    ],
  },
  {
    name: 'land',
    description: 'Saved farm/property',
    source: 'projects/home/src/app/models/map.models.ts#SavedFarm',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'farmer_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'farmer', column: 'id' },
      },
      {
        name: 'name',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
      },
      {
        name: 'total_area',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
        description: 'Total area in hectares or acres',
      },
      {
        name: 'area_unit',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
        description: 'Unit of measurement (e.g., "hectare", "acre")',
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
      {
        name: 'updated_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
      {
        name: 'deleted_at',
        tsType: 'datetime | null',
        sqlType: 'timestamp with time zone',
        nullable: true,
      },
    ],
  },
  {
    name: 'land_point',
    description: 'Boundary point for a land/farm polygon',
    source: 'projects/home/src/app/models/map.models.ts#LatLngPoint (array)',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'land_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'land', column: 'id' },
      },
      {
        name: 'sequence',
        tsType: 'number',
        sqlType: 'integer',
        nullable: false,
        description: 'Order in polygon boundary (0-indexed)',
      },
      {
        name: 'latitude',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: false,
      },
      {
        name: 'longitude',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: false,
      },
    ],
  },
  {
    name: 'crop',
    description: 'Crop planted on a land',
    source: 'projects/home/src/app/models/crop-timeline.models.ts#CropEntity',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'farmer_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'farmer', column: 'id' },
      },
      {
        name: 'land_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'land', column: 'id' },
      },
      {
        name: 'name',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
      },
      {
        name: 'variety',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'sowing_date',
        tsType: 'string',
        sqlType: 'date',
        nullable: true,
      },
      {
        name: 'expected_harvest_date',
        tsType: 'string',
        sqlType: 'date',
        nullable: true,
      },
      {
        name: 'area',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'area_unit',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'status',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
        description: 'Status: active, harvested, abandoned, etc.',
      },
      {
        name: 'notes',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
      {
        name: 'updated_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
      {
        name: 'deleted_at',
        tsType: 'datetime | null',
        sqlType: 'timestamp with time zone',
        nullable: true,
      },
    ],
  },
  {
    name: 'activity',
    description: 'Farm activity (irrigation, spraying, harvesting, etc.)',
    source: 'projects/backend/myfarm_api/schemas/activity.py#Activity',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'farmer_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'farmer', column: 'id' },
      },
      {
        name: 'activity_type_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        description: 'Reference to activity type (irrigation, spray, etc.)',
      },
      {
        name: 'crop_id',
        tsType: 'UUID | null',
        sqlType: 'uuid',
        nullable: true,
        fk: { table: 'crop', column: 'id' },
      },
      {
        name: 'land_id',
        tsType: 'UUID | null',
        sqlType: 'uuid',
        nullable: true,
        fk: { table: 'land', column: 'id' },
      },
      {
        name: 'parent_activity_id',
        tsType: 'UUID | null',
        sqlType: 'uuid',
        nullable: true,
        fk: { table: 'activity', column: 'id' },
        description: 'For sub-activities (e.g., spray rounds under a campaign)',
      },
      {
        name: 'custom_activity_name',
        tsType: 'string | null',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'date',
        tsType: 'string',
        sqlType: 'date',
        nullable: true,
      },
      {
        name: 'season',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'status',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
        description: 'pending, completed, cancelled, etc.',
      },
      {
        name: 'notes',
        tsType: 'string | null',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'metadata',
        tsType: 'Record<string, any>',
        sqlType: 'jsonb',
        nullable: true,
        description: 'Activity-type-specific fields: irrigation volume, spray chemicals, harvest yield, etc.',
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
      {
        name: 'updated_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
      {
        name: 'deleted_at',
        tsType: 'datetime | null',
        sqlType: 'timestamp with time zone',
        nullable: true,
      },
    ],
  },
  {
    name: 'activity_expense',
    description: 'Cost tracking for an activity',
    source: 'projects/backend/myfarm_api/schemas/activity.py#ActivityExpense (inferred)',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'activity_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'activity', column: 'id' },
      },
      {
        name: 'expense_type',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
        description: 'Category: labor, material, fuel, equipment, etc.',
      },
      {
        name: 'amount',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: false,
      },
      {
        name: 'currency',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
        description: 'Currency code (e.g., USD, INR)',
      },
      {
        name: 'description',
        tsType: 'string | null',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
      {
        name: 'updated_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
    ],
  },
  {
    name: 'activity_attachment',
    description: 'Files/images attached to an activity (out-of-row storage)',
    source: 'projects/home/src/app/models/backup.models.ts#Activity.attachments[] (formalized)',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'activity_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'activity', column: 'id' },
      },
      {
        name: 'filename',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
      },
      {
        name: 'mime_type',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
      },
      {
        name: 'data_uri',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
        description: 'Base64-encoded file data as data: URI',
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
    ],
  },
  {
    name: 'weather_snapshot',
    description: 'Current weather at a location on a date',
    source: 'projects/home/src/app/models/weather.models.ts#CurrentWeather',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'farmer_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'farmer', column: 'id' },
      },
      {
        name: 'location',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
        description: 'Location name or identifier',
      },
      {
        name: 'latitude',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: false,
      },
      {
        name: 'longitude',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: false,
      },
      {
        name: 'date',
        tsType: 'string',
        sqlType: 'date',
        nullable: false,
      },
      {
        name: 'temperature',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'humidity',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'pressure',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'wind_speed',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'wind_direction',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'precipitation',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'description',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
    ],
  },
  {
    name: 'weather_forecast_day',
    description: 'Forecast for one day at a location',
    source: 'projects/home/src/app/models/weather.models.ts#ForecastDay',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'farmer_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'farmer', column: 'id' },
      },
      {
        name: 'location',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
      },
      {
        name: 'latitude',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: false,
      },
      {
        name: 'longitude',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: false,
      },
      {
        name: 'date',
        tsType: 'string',
        sqlType: 'date',
        nullable: false,
      },
      {
        name: 'forecast_date',
        tsType: 'string',
        sqlType: 'date',
        nullable: false,
        description: 'The date being forecast',
      },
      {
        name: 'min_temperature',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'max_temperature',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'precipitation_probability',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'expected_precipitation',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'humidity',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'wind_speed',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: true,
      },
      {
        name: 'description',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
    ],
  },
  {
    name: 'weather_alert',
    description: 'Weather alert (frost, drought, excess rain, etc.)',
    source: 'projects/home/src/app/models/weather.models.ts#WeatherAlert',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'farmer_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'farmer', column: 'id' },
      },
      {
        name: 'location',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
      },
      {
        name: 'latitude',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: false,
      },
      {
        name: 'longitude',
        tsType: 'number',
        sqlType: 'numeric',
        nullable: false,
      },
      {
        name: 'alert_type',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
        description: 'frost, drought, excess_rain, heat_wave, pest_risk, etc.',
      },
      {
        name: 'severity',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
        description: 'low, medium, high, critical',
      },
      {
        name: 'date',
        tsType: 'string',
        sqlType: 'date',
        nullable: false,
      },
      {
        name: 'description',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'recommendation',
        tsType: 'string',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
    ],
  },
  {
    name: 'role',
    description: 'RBAC role definition (proposed, not yet wired)',
    source: 'Proposed for future RBAC implementation',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'name',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
        unique: true,
      },
      {
        name: 'description',
        tsType: 'string | null',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
    ],
  },
  {
    name: 'farmer_role',
    description: 'Assignment of roles to farmers (proposed)',
    source: 'Proposed for future RBAC implementation',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'farmer_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'farmer', column: 'id' },
      },
      {
        name: 'role_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'role', column: 'id' },
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
    ],
  },
  {
    name: 'module',
    description: 'Feature module for permission scoping (proposed)',
    source: 'Proposed for future RBAC implementation',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'name',
        tsType: 'string',
        sqlType: 'text',
        nullable: false,
        unique: true,
      },
      {
        name: 'description',
        tsType: 'string | null',
        sqlType: 'text',
        nullable: true,
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
    ],
  },
  {
    name: 'role_module',
    description: 'Permissions: role grants access to module (proposed)',
    source: 'Proposed for future RBAC implementation',
    fields: [
      {
        name: 'id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        pk: true,
      },
      {
        name: 'role_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'role', column: 'id' },
      },
      {
        name: 'module_id',
        tsType: 'UUID',
        sqlType: 'uuid',
        nullable: false,
        fk: { table: 'module', column: 'id' },
      },
      {
        name: 'created_at',
        tsType: 'datetime',
        sqlType: 'timestamp with time zone',
        nullable: false,
      },
    ],
  },
];
